spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payme
    username: Admin
    password: Admin
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.transaction : TRACE
    org.springframework.transaction.support: TRACE
    org.springframework.transaction.interceptor : TRACE
    com.zaxxer.hikari.pool.HikariPool: DEBUG

